<?php
    require_once('../src/controllers/contact.php');
    ob_start();

    $pageTitle = 'Contact';
?>

<section id="contact-form" class="form my-5">
    <form action="contact" method="POST" class="d-flex f-col g-2 w25 m-auto">
        <input type="text" name="name" id="name" placeholder="Your Name">
        <input type="text" name="mail" id="mail" placeholder="Your E-mail">
        <input type="text" name="subject" id="subject" placeholder="subject">
        <input type="text" name="message" id="message" placeholder="Your Message">
        <input type="submit" value="send !" name="submit">
    </form>
</section>

<?php
$content = ob_get_clean();
require_once('../src/views/template/layout.phtml');
?>