<?php
    require_once('../src/controllers/library-user.php');
    ob_start();

    $pageTitle = 'My library';
?>

<h1 class="txt-center color-light">Easy Mangas</h1>
<section id="mangas-grid" class="container grid g-2 mt-2 m-auto w-auto">
    <?php
    foreach ($mangas as $manga) { ?>
        <article id="manga-card-<?php echo $manga['id'] ?>"class="manga-card col-12 col-md-6 col-lg-4 col-xl-3 bg-light p-2">
            <header class="manga-card-header my-2">
                <img class="txt-center w100" src="./img/dist/<?php echo $manga['img'] ?>" alt=<?php echo 'preview of : ' . $manga['name'] ?>>
                <h3 class="manga-header-name color-dark txt-center"><?php echo $manga['name'] ?></h3>
            </header>
            <div class="manga-card-body txt-center d-flex f-col g-1 my-1">
                <h4 class="manga-card-author color-dark">Author : <?php echo $manga['author'] ?></h4>
                <h4 class="manga-card-editor color-dark">Editor : <?php echo $manga['editor'] ?></h4>
                <h6 class="manga-card-tomes color-dark">Nb tomes : <?php echo $manga['tomes'] ?></h6>
                <p class="manga-card-tomes-read color-dark">You read the : <?php echo $manga['tomes_read'] ?> first tomes !</p>
            </div>
            <footer class="manga-card-footer d-flex x-flex-center mb-2">
                <a class="p-1 bg-dark color-light" href="delete-to-library?mangaId=<?php echo $manga['id'] ?>">Delete of my library</a>
            </footer>
            <div class="input-tomes">
                <h4 class="txt-center my-1 color-dark">change tome numbers read :</h4>
                <form action="library-user" method="POST" class="d-flex g-1">
                    <input type="number" class="d-block w-25 m-auto" value="<?php echo $manga['tomes_read'] ?>" name="user-tomes-read">
                    <input type="hidden" name="id-manga" value="<?php echo $manga['id'] ?>">
                    <input type="submit" value="submit" class="d-block w-75 m-auto" name="submit">
                </form>
            </div>
        </article>
    <?php } ?>
</section>
<?php
$content = ob_get_clean();
require_once('../src/views/template/layout.phtml');
?>