<?php
    require_once(__DIR__ . './../controllers/new-manga.php');
?>
<form action="./src/controllers/new-manga" method="POST" enctype="multipart/form-data">
    <input type="text" name="name" id="name">
    <input type="text" name="author" id="author">
    <input type="text" name="editor" id="editor">
    <input type="number" name="tomes" id="tomes">
    <input type="text" name="resume" id="resume">
    <input type="file" id="img" name="img">
    <input type="submit" value="Subscribe !" name="submit">
</form>


