<?php
    require_once(__DIR__ . './../controllers/new-manga.php');
    ob_start();
    
    $pageTitle = 'New manga';
    
    if (isset($_SESSION['msg'])) {
        $msg = $_SESSION['msg'];
    }
?>
<?php 
    if (isset($msg)) { ?>
        <h3 class="title txt-center my-2 color-main"><?php echo $msg ?></h3>
    <?php } 
?>
<section id="subscribe-form" class="form my-5">
    <form action="new-manga" method="POST" enctype="multipart/form-data" class="d-flex f-col g-2 w25 m-auto">
        <input type="text" name="name" id="name" placeholder="Name of manga">
        <input type="text" name="author" id="author" placeholder="Author of manga">
        <input type="text" name="editor" id="editor" placeholder="Editor of manga">
        <input type="number" name="tomes" id="tomes" placeholder="Tome's number of manga">
        <input type="text" name="resume" id="resume" placeholder="Resume of manga">
        <input type="file" id="img" name="img">
        <input type="submit" value="Submit !" name="submit">
    </form>
</section>
<?php
    $content = ob_get_clean();
    require_once('../src/views/template/layout.phtml'); 
?>


