<?php
require_once(__DIR__ . './../controllers/user-administration.php');
ob_start();
$pageTitle = 'User administration';
?>
<h1 class="txt-center color-main">Users Administration</h1>

<section id="users-admin-grid" class="container grid g-2 mt-2 m-auto w-auto">
    <?php foreach ($getUsers as $user) { ?>
        <article class="user-card col-12 col-md-6 col-lg-4 col-xl-3 bg-light p-2">
            <header class="user-card-header my-2">
                <h3 class="user-header-pseudo color-dark txt-center"><?php echo $user['pseudo'] ?></h3>
            </header>
            <div class="user-card-body txt-center d-flex f-col g-1 my-2">
                <h4 class="user-card-mail color-dark">User mail : <?php echo $user['mail'] ?></h4>
                <h4 class="user-card-role color-dark">User role : <?php echo $user['name'] ?></h4>
            </div>
            <footer class="user-card-footer txt-center">
                <a class="p-1 bg-dark color-light" href="src/controllers/user-administration?idUserToDelete=<?php echo $user['id'] ?>">Delete this user</a><br><br><br>
                <a class="p-1 bg-dark color-light" href="user-edit?idUser=<?php echo $user['id'] ?>">Edit user</a>
            </footer>
        </article>
    <?php } ?>
</section>

<?php
$content = ob_get_clean();
require_once('../src/views/template/layout.phtml');
?>