<?php
    require_once(__DIR__ . './../controllers/user-edit.php');
    $idUser = $_GET['idUser'];
?>
<form action="./user-edit.phtml?"<?php echo $idUser; ?> method="POST">
    <input type="hidden" name="idUser" value=<?php echo $idUser; ?>>
    <input type="text" name="pseudo" id="pseudo">
    <input type="text" name="mail" id="mail">
    <input type="text" name="password" id="password">
    <input type="hidden" name="role" id="role" value=2>
    <input type="submit" value="Subscribe !" name="submit">
</form>

