</main>
<footer id="main-footer"  class="bg-light mt-10 p-1 w100">
    <h3 class="color-dark txt-center">Made with ❤ || by <a target="blank" href="https://portfolio-dupau-jonathan.000webhostapp.com/"> <span class="color-main">Jonathan Dupau Web developer junior</span></a></h3>
</footer>
</body>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
  AOS.init();
</script>
<script src="./js/dist/scripts.min.js"></script>
</html>