<!DOCTYPE html>
<html lang="en">
<?php
    $pageTitle = $pageTitle ?? '';
?>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EasyManga | <?php echo $pageTitle ?>
    </title>
    <link rel="stylesheet" href="./../public/css/dist/style.min.css">
</head>

<body>
    <header id="main-header">
        <a id="main-logo" href="index"><img src="" alt="Logo Easy Mangas"></a>
        <nav>
            <a href="index">INDEX</a>
            <a href="subscribe">SUBSCRIBE</a>
            <a href="test-detailuser">DETAIL</a>
            <a href="user-administration">USER-ADMIN</a>
            <a href="user-edit">USER EDIT</a>
        </nav>
    </header>