<!DOCTYPE html>
<html lang="en">
<?php
    $pageTitle = $pageTitle ?? '';
    if (isset($_SESSION['user']['id'])) {
        $idUser = $_SESSION['user']['id'];
    } else {
        $_SESSION['user']['poid'] = 0;
    }
?>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EasyManga | <?php echo $pageTitle ?>
    </title>
    <link rel="stylesheet" href="./css/dist/style.min.css">
    <link rel="stylesheet" href="./css/framework/config.css">
    <link rel="stylesheet" href="./css/framework/layout.css">
    <link rel="stylesheet" href="./css/framework/reboot.css">
    <link rel="stylesheet" href="./css/framework/utilities.css">
</head>

<body class="bg-dark">
    <header id="main-header" class="d-flex f-row x-flex-between bg-light">
        <a id="main-logo" href="index"><img src="" alt="Logo Easy Mangas"></a>
        <nav class="d-flex f-row g-1 p-2">
            <?php 
                if (basename($_SERVER['REQUEST_URI']) != 'index') { ?>
                    <a class="p-1 bg-dark color-light" href="index">INDEX</a>
            <?php } ?>
            <?php 
                if (isset($_SESSION['user']['id']) && basename($_SERVER['REQUEST_URI']) != 'library-user') { ?>
                    <a class="p-1 bg-dark color-light" href="library-user">MY LIBRARY</a>
            <?php } ?>
            <?php 
                if (isset($_SESSION['user']['id']) && basename($_SERVER['REQUEST_URI']) != 'manga-administration' && $_SESSION['user']['poid'] >= 50) { ?>
                    <a class="p-1 bg-dark color-light" href="manga-administration">MANGA-ADMIN</a>
            <?php } ?>

            <!-- <?php 
                if (isset($_SESSION['user']['id']) && basename($_SERVER['REQUEST_URI']) != 'test-detailuser') { ?>
                    <a class="p-1 bg-dark color-light" href="test-detailuser?idUser=<?php echo $idUser ?>">DETAIL</a>
            <?php } ?> -->
            <?php 
                if (isset($_SESSION['user']['id']) && basename($_SERVER['REQUEST_URI']) != 'user-administration' && $_SESSION['user']['poid'] > 50) { ?>
                    <a class="p-1 bg-dark color-light" href="user-administration">USER-ADMIN</a>
            <?php } ?>
            <?php 
                if (!isset($_SESSION['user']['id']) && basename($_SERVER['REQUEST_URI']) != 'subscribe') { ?>
                    <a class="p-1 bg-dark color-light" href="subscribe">SUBSCRIBE</a>
            <?php } ?>
            <?php 
                if (!isset($_SESSION['user']['id']) && basename($_SERVER['REQUEST_URI']) != 'login') { ?>
                    <a class="p-1 bg-dark color-light" href="login">LOGIN</a>
            <?php } ?>
            <?php 
                if (isset($_SESSION['user']['id'])) { ?>
                    <a class="p-1 bg-dark color-light" href="logout">LOGOUT</a>
            <?php } ?>
        </nav>
    </header>


